### ISSUE TITLE
npm install not installing jbrowse on ubuntu

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbconnect#60]
npm install
npm WARN deprecated filesaver.js@0.2.0: Unmaintained namespace. Please use the file-saver package: https://www.npmjs.com/package/file-saver
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> typechecker@2.0.8 preinstall /home/ericiam/jbserver/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

> typechecker@2.0.8 preinstall /home/ericiam/jbserver/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js

> fibers@2.0.0 install /home/ericiam/jbserver/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory '/home/ericiam/jbserver/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc: In function ‘void uni::SetAccessor(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, uni::FunctionType (*)(v8::Local<v8::String>, const GetterCallbackInfo&), void (*)(v8::Local<v8::String>, v8::Local<v8::Value>, const SetterCallbackInfo&))’:
../src/fibers.cc:318:129: warning: ignoring return value of ‘v8::Maybe<bool> v8::Object::SetAccessor(v8::Local<v8::Context>, v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::MaybeLocal<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’, declared with attribute warn_unused_result [-Wunused-result]
 ->GetCurrentContext(), name, (AccessorNameGetterCallback)getter, (AccessorNameSetterCallback)setter);
                                                                                                    ^
In file included from /home/ericiam/.node-gyp/9.6.0/include/node/node.h:63:0,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/home/ericiam/.node-gyp/9.6.0/include/node/v8.h:3240:37: note: declared here
   V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(Local<Context> context,
                                     ^~~~~~~~~~~
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory '/home/ericiam/jbserver/node_modules/fibers/build'
Installed in `/home/ericiam/jbserver/node_modules/fibers/bin/linux-x64-59/fibers.node`

> deasync@0.1.12 install /home/ericiam/jbserver/node_modules/deasync
> node ./build.js

`linux-x64-node-9` exists; testing
Binary is fine; exiting

> chromedriver@2.35.0 install /home/ericiam/jbserver/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Received 781K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3634K total.
Extracting zip contents
Copying to target path /home/ericiam/jbserver/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /home/ericiam/jbserver/node_modules/chromedriver/lib/chromedriver/chromedriver

> phantomjs-prebuilt@2.1.16 install /home/ericiam/jbserver/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/ericiam/jbserver/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1519361497103/phantomjs-2.1.1-linux-x86_64 -> /home/ericiam/jbserver/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/ericiam/jbserver/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> jbserver@0.0.101 postinstall /home/ericiam/jbserver
> node ./bin/postinstall.js

Database already exists: /home/ericiam/jbserver/data/
Installing JBrowse sample data...
/bin/sh: 1: ./jb_setup.js: not found
added 1626 packages in 87.929s

**Comment by enuggetry** [comment]
seems to be working fine with CentOS 7.

**Comment by enuggetry** [comment]
On Centos 7.4
$ git clone http://github.com/gmod/jbserver
Cloning into 'jbserver'...
remote: Counting objects: 8842, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 8842 (delta 0), reused 2 (delta 0), pack-reused 8837
Receiving objects: 100% (8842/8842), 7.38 MiB | 0 bytes/s, done.
Resolving deltas: 100% (4299/4299), done.
[ericiam@ip-172-30-2-63 ~]$ cd jbserver
[ericiam@ip-172-30-2-63 jbserver]$ npm install
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated ejs@2.3.4: Critical security bugs fixed in 2.5.5
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm WARN deprecated constantinople@3.0.2: Please update to at least constantinople 3.1.1
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated ejs@0.8.8: Critical security bugs fixed in 2.5.5
npm WARN deprecated geojsonhint@1.2.1: This module is now under the @mapbox namespace: install @mapbox/geojsonhint instead
npm WARN deprecated native-or-bluebird@1.1.2: 'native-or-bluebird' is deprecated. Please use 'any-promise' instead.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated filesaver.js@0.2.0: Unmaintained namespace. Please use the file-saver package: https://www.npmjs.com/package/file-saver
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> typechecker@2.0.8 preinstall /home/ericiam/jbserver/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /home/ericiam/jbserver/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> fibers@2.0.0 install /home/ericiam/jbserver/node_modules/fibers
> node build.js || nodejs build.js

`linux-x64-57` exists; testing
Problem with the binary; manual build incoming
make: Entering directory `/home/ericiam/jbserver/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/home/ericiam/jbserver/node_modules/fibers/build'
Installed in `/home/ericiam/jbserver/node_modules/fibers/bin/linux-x64-57/fibers.node`

> deasync@0.1.12 install /home/ericiam/jbserver/node_modules/deasync
> node ./build.js

`linux-x64-node-8` exists; testing
Binary is fine; exiting

> chromedriver@2.35.0 install /home/ericiam/jbserver/node_modules/chromedriver
> node install.js

Downloading https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
Saving to /tmp/chromedriver/chromedriver_linux64.zip
Received 781K...
Received 1568K...
Received 2352K...
Received 3136K...
Received 3634K total.
Extracting zip contents
Copying to target path /home/ericiam/jbserver/node_modules/chromedriver/lib/chromedriver
Fixing file permissions
Done. ChromeDriver binary available at /home/ericiam/jbserver/node_modules/chromedriver/lib/chromedriver/chromedriver

> phantomjs-prebuilt@2.1.16 install /home/ericiam/jbserver/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...
  [----------------------------------------] 0%
Received 22866K total.
Extracting tar contents (via spawned process)
Error extracting archive
Phantom installation failed { Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2' } Error: Command failed: tar jxf /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar (child): bzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ericiam/.npm/_logs/2018-02-23T06_13_50_801Z-debug.log
