### ISSUE TITLE
/register fails to load

### ISSUE THREAD

**Issue by enuggetry** [GMOD/jbconnect#80]
{
  "stack": "ReferenceError: /home/ericiam/jbconnect/views/auth/bregister.ejs:59\n    57|         \n    58|     </style>\n >> 59|     <%\n    60|         const test = require('')\n    61|     %>\n    62|   </head>\n\nrequire is not defined\n    at eval (eval at exports.compile (/home/ericiam/jbconnect/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:31:22)\n    at eval (eval at exports.compile (/home/ericiam/jbconnect/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:237:14), <anonymous>:32:6089)\n    at /home/ericiam/jbconnect/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:250:15\n    at Object.exports.render (/home/ericiam/jbconnect/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:288:13)\n    at Object.exports.renderFile (/home/ericiam/jbconnect/node_modules/ejs-locals/node_modules/ejs/lib/ejs.js:318:20)\n    at SailsView.module.exports [as engine] (/home/ericiam/jbconnect/node_modules/ejs-locals/index.js:85:7)\n    at SailsView.View.render (/home/ericiam/jbconnect/node_modules/@sailshq/express/lib/view.js:76:8)\n    at Function.app.render (/home/ericiam/jbconnect/node_modules/@sailshq/express/lib/application.js:561:10)\n    at ServerResponse.res.render (/home/ericiam/jbconnect/node_modules/@sailshq/express/lib/response.js:845:7)\n    at ServerResponse.res.view (/home/ericiam/jbconnect/node_modules/sails/lib/hooks/views/res.view.js:284:16)\n    at Object.register (/home/ericiam/jbconnect/api/controllers/AuthController.js:124:9)\n    at wrapper (/home/ericiam/jbconnect/node_modules/@sailshq/lodash/lib/index.js:3275:19)\n    at routeTargetFnWrapper (/home/ericiam/jbconnect/node_modules/sails/lib/router/bind.js:181:5)\n    at callbacks (/home/ericiam/jbconnect/node_modules/@sailshq/express/lib/router/index.js:164:37)\n    at param (/home/ericiam/jbconnect/node_modules/@sailshq/express/lib/router/index.js:138:11)\n    at pass (/home/ericiam/jbconnect/node_modules/@sailshq/express/lib/router/index.js:145:5)\n    at nextRoute (/home/ericiam/jbconnect/node_modules/@sailshq/express/lib/router/index.js:100:7)\n    at callbacks (/home/ericiam/jbconnect/node_modules/@sailshq/express/lib/router/index.js:167:11)\n    at /home/ericiam/jbconnect/api/policies/passport.js:34:7\n    at SessionStrategy.strategy.pass (/home/ericiam/jbconnect/node_modules/passport/lib/middleware/authenticate.js:325:9)\n    at /home/ericiam/jbconnect/node_modules/passport/lib/strategies/session.js:65:12\n    at pass (/home/ericiam/jbconnect/node_modules/passport/lib/authenticator.js:327:31)\n    at deserialized (/home/ericiam/jbconnect/node_modules/passport/lib/authenticator.js:339:7)\n    at returnResults (/home/ericiam/jbconnect/node_modules/waterline/lib/waterline/query/finders/basic.js:179:9)\n    at /home/ericiam/jbconnect/node_modules/waterline/lib/waterline/query/finders/basic.js:86:16\n    at /home/ericiam/jbconnect/node_modules/waterline/lib/waterline/query/finders/operations.js:83:7\n    at /home/ericiam/jbconnect/node_modules/waterline/node_modules/async/lib/async.js:52:16\n    at Object.async.forEachOf.async.eachOf (/home/ericiam/jbconnect/node_modules/waterline/node_modules/async/lib/async.js:236:30)\n    at Object.async.forEach.async.each (/home/ericiam/jbconnect/node_modules/waterline/node_modules/async/lib/async.js:209:22)\n    at /home/ericiam/jbconnect/node_modules/waterline/lib/waterline/query/finders/operations.js:436:11\n    at /home/ericiam/jbconnect/node_modules/waterline/lib/waterline/query/finders/operations.js:574:5\n    at /home/ericiam/jbconnect/node_modules/waterline/node_modules/async/lib/async.js:52:16\n    at Object.async.forEachOf.async.eachOf (/home/ericiam/jbconnect/node_modules/waterline/node_modules/async/lib/async.js:236:30)\n    at Object.async.forEach.async.each (/home/ericiam/jbconnect/node_modules/waterline/node_modules/async/lib/async.js:209:22)",
  "message": "/home/ericiam/jbconnect/views/auth/bregister.ejs:59\n    57|         \n    58|     </style>\n >> 59|     <%\n    60|         const test = require('')\n    61|     %>\n    62|   </head>\n\nrequire is not defined",
  "path": "/home/ericiam/jbconnect/views/auth/bregister.ejs"
}

**Comment by enuggetry** [comment]
Resolved
